Consumer_Key:        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
Consumer_Secret:     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

Request_token_URL:   "https://api.zaim.net/v1/auth/request"
Authorize_URL:       "https://www.zaim.net/users/auth"
Access_token_URL:    "https://api.zaim.net/v1/auth/access"
